generator: admingenerator.generator.doctrine
params:
    model: Acme\TestBundle\Entity\Block
    namespace_prefix: Acme
    concurrency_lock: ~
    bundle_name: TestBundle
    embed_types:
        - "Acme:TestBundle:Block-generator.yml"
    pk_requirement: ~
    fields:
        children:
            dbType: collection
            formType: afe_collection_table
            addFormOptions:
                type: edit_block2
                allow_add: true
                allow_delete: true
                prototype_name: __block__
                by_reference: false
                options:
                    data_class: Acme\TestBundle\Entity\Block
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: List for TestBundle
            display: ~
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display: ~
    new:
        params:
            title: New object for TestBundle
            display: ~
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the object \"%object%\"|{ %object%: Block.title }|"
            display: [title, content, children]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: Block.title }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
