<?php

namespace Acme\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageTranslationBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageTranslationBlockRepository extends EntityRepository
{
}
